### PR TITLE
Allow for excluding files and directories from Visualizer processing

### LINKED ISSUE #60: Include file and folder exclusions in the visualiser function
Currently there is no option to exclude certain folders or files in the visualiser function. This means that if a model being reviewed has some error in a file, the code won't run and the visual won't be created. One solution to this is for the reviewer to edit the original source code, but it would be preferential to be able to ignore that file and proceed.

https://github.com/dark-peak-analytics/assertHE/blob/90b8ddef23829701b9fe238f4fb31d80f4864097/R/project_visualiser.R#L33

I think this involves:
- adding a new argument for files to exclude from foo and tests.
- `assertHE::summarise_model` to include exclusions on tests and functions - while doing this a project path should be added.
- `get_foo_coverage` to include exclusions on tests and functions - also add project path here & ensure tests/functions are relative to this.
-  `source_files` has an exclusion argument, add excluded files to this.

### PR DESCRIPTION
**Pull request by Smit-tay**
Fixes #60

### CODE REVIEW

**Comment by Smit-tay** [comment]
Works as expected for me.

find_files(file_regx = ".R",  ## any R file
 path = ".",   # the current directory and all subdirectories
 recursive = TRUE,  
 exclude_files = NULL,
 exclude_dirs = "R"  # exclude any directory named "R", or subdirs
 )
 
 This returns the following list:
 
 [1] "./assertHE.Rproj"                                                                            
  [2] "./CONTRIBUTING.md"                                                                           
  [3] "./DESCRIPTION"                                                                               
  [4] "./inst/example_script/create_markov_trace.R"                                                 
  [5] "./inst/example_script/define_transition_matrix.R"                                            
  [6] "./inst/example_script/example_script.R"                                                      
  [7] "./man/check_init.Rd"                                                                         
  [8] "./man/check_markov_trace.Rd"                                                                 
  [9] "./man/check_trans_prob_array.Rd"                                                             
 [10] "./man/check_trans_prob_mat.Rd"                                                               
 [11] "./man/create_prompt.Rd"                                                                      
 [12] "./man/define_app_server.Rd"                                                                  
 [13] "./man/define_app_ui.Rd"                                                                      
 [14] "./man/dot-called_by.Rd"                                                                      
 [15] "./man/dot-parse_function.Rd"                                                                 
 [16] "./man/extract_function_name.Rd"                                                              
 [17] "./man/find_files.Rd"                                                                         
 [18] "./man/find_folder_function_definitions.Rd"                                                   
 [19] "./man/find_function_calls_in_file.Rd"                                                        
 [20] "./man/find_function_calls_in_folder.Rd"                                                      
 [21] "./man/find_function_definitions.Rd"                                                          
 [22] "./man/find_next_vector_element.Rd"                                                           
 [23] "./man/find_previous_vector_element.Rd"                                                       
 [24] "./man/get_active_functions.Rd"                                                               
 [25] "./man/get_file_cheers_classifications.Rd"                                                    
 [26] "./man/get_folder_cheers_classifications.Rd"                                                  
 [27] "./man/get_foo_coverage.Rd"                                                                   
 [28] "./man/get_function_data.Rd"                                                                  
 [29] "./man/get_function_line.Rd"                                                                  
 [30] "./man/get_function_path.Rd"                                                                  
 [31] "./man/get_isolated_foo.Rd"                                                                   
 [32] "./man/get_roxygen_description_from_foo.Rd"                                                   
 [33] "./man/get_roxygen_description.Rd"                                                            
 [34] "./man/identify_dependencies.Rd"                                                              
 [35] "./man/locate_funcs.Rd"                                                                       
 [36] "./man/make_closable_tab.Rd"                                                                  
 [37] "./man/plot_PSA_stability.Rd"                                                                 
 [38] "./man/plotNetwork.Rd"                                                                        
 [39] "./man/processNodes.Rd"                                                                       
 [40] "./man/return_message.Rd"                                                                     
 [41] "./man/run_shiny_app.Rd"                                                                      
 [42] "./man/source_files.Rd"                                                                       
 [43] "./man/source_funcs.Rd"                                                                       
 [44] "./man/source_lines.Rd"                                                                       
 [45] "./man/summarise_function_from_arguments_and_body.Rd"                                         
 [46] "./man/summarise_function_with_LLM.Rd"                                                        
 [47] "./man/summarise_model.Rd"                                                                    
 [48] "./man/visualise_project.Rd"                                                                  
 [49] "./man/wrap_string.Rd"                                                                        
 [50] "./README.Rmd"                                                                                
 [51] "./tests/testthat.R"                                                                          
 [52] "./tests/testthat/cdx2cea_master/analysis/_master.R"                                          
 [53] "./tests/testthat/cdx2cea_master/analysis/01_model_inputs.R"                                  
 [54] "./tests/testthat/cdx2cea_master/analysis/02_decision_model.R"                                
 [55] "./tests/testthat/cdx2cea_master/analysis/03_calibration.R"                                   
 [56] "./tests/testthat/cdx2cea_master/analysis/04_validation.R"                                    
 [57] "./tests/testthat/cdx2cea_master/analysis/05a_probabilistic_analysis.R"                       
 [58] "./tests/testthat/cdx2cea_master/analysis/05b_deterministic_analysis.R"                       
 [59] "./tests/testthat/cdx2cea_master/analysis/05c_value_of_information.R"                         
 [60] "./tests/testthat/cdx2cea_master/data-raw/01_all_cause_mortality.R"                           
 [61] "./tests/testthat/cdx2cea_master/data-raw/03_calibration_targets.R"                           
 [62] "./tests/testthat/cdx2cea_master/data-raw/03_imis_output.R"                                   
 [63] "./tests/testthat/cdx2cea_master/data-raw/05a_psa_dataset.R"                                  
 [64] "./tests/testthat/cdx2cea_master/data/03_calibration_targets.RData"                           
 [65] "./tests/testthat/cdx2cea_master/data/03_summary_posterior.RData"                             
 [66] "./tests/testthat/cdx2cea_master/data/05a_probabilistic_cea_results.RData"                    
 [67] "./tests/testthat/cdx2cea_master/data/05b_owsa_icer.RData"                                    
 [68] "./tests/testthat/cdx2cea_master/data/05b_twsa_icer_hrRecurCDX2neg_vs_hrCDX2negtrt.RData"     
 [69] "./tests/testthat/cdx2cea_master/data/05b_twsa_icer_pCDX2_vs_hrCDX2negtrt_50k.RData"          
 [70] "./tests/testthat/cdx2cea_master/data/05b_twsa_icer_pCDX2_vs_hrCDX2negtrt.RData"              
 [71] "./tests/testthat/cdx2cea_master/data/05b_twsa_nmb_hrRecurCDX2neg_vs_hrCDX2negtrt_100k.RData" 
 [72] "./tests/testthat/cdx2cea_master/data/05b_twsa_nmb_hrRecurCDX2neg_vs_hrCDX2negtrt_50k.RData"  
 [73] "./tests/testthat/cdx2cea_master/data/05b_twsa_nmb_pCDX2_vs_hrCDX2negtrt_100k.RData"          
 [74] "./tests/testthat/cdx2cea_master/data/05b_twsa_nmb_pCDX2_vs_hrCDX2negtrt_50k.RData"           
 [75] "./tests/testthat/cdx2cea_master/tests/testthat.R"                                            
 [76] "./tests/testthat/cdx2cea_master/tests/testthat/test_02_simulation_model_functions.R"         
 [77] "./tests/testthat/cdx2cea_master/tests/testthat/test_05a_deterministic_analysis_function.R"   
 [78] "./tests/testthat/example_project/model.R"                                                    
 [79] "./tests/testthat/example_project/tests/testthat.R"                                           
 [80] "./tests/testthat/example_project/tests/testthat/fixtures/make-useful-things.R"               
 [81] "./tests/testthat/example_project/tests/testthat/test-calculate_costs.R"                      
 [82] "./tests/testthat/example_project/tests/testthat/test-calculate_discounting_weights.R"        
 [83] "./tests/testthat/example_project/tests/testthat/test-calculate_QALYs.R"                      
 [84] "./tests/testthat/example_project/tests/testthat/test-create_Markov_trace.R"                  
 [85] "./tests/testthat/example_project/tests/testthat/test-define_transition_matrix.R"             
 [86] "./tests/testthat/example_project/tests/testthat/test-run_sickSicker_model.R"                 
 [87] "./tests/testthat/example_project/tests/testthat/test-utility_functions_with_different_name.R"
 [88] "./tests/testthat/example_scripts/create_markov_trace.R"                                      
 [89] "./tests/testthat/example_scripts/define_transition_matrix.R"                                 
 [90] "./tests/testthat/example_scripts/example_script.R"                                           
 [91] "./tests/testthat/example_scripts/example_tricky_functions.R"                                 
 [92] "./tests/testthat/example_scripts/no_funcs.R"                                                 
 [93] "./tests/testthat/test-check_functions.R"                                                     
 [94] "./tests/testthat/test-check_init.R"                                                          
 [95] "./tests/testthat/test-check_markov_trace.R"                                                  
 [96] "./tests/testthat/test-check_PSAstability.R"                                                  
 [97] "./tests/testthat/test-check_trans_probs.R"                                                   
 [98] "./tests/testthat/test-check_utility.R"                                                       
 [99] "./tests/testthat/test-cheers_checker.R"                                                      
[100] "./tests/testthat/test-get_foo_coverage.R"                                                    
[101] "./tests/testthat/test-project_visualiser.R"                                                  
[102] "./tests/testthat/test-test_finder.R"  

There are no directories with an uppercase R in the directory name in this list

**Comment by RobertASmith** [comment]
Strange, works the same as yours now. This solves the issue for one directory/file.

OK so minor bugs/enhancements:
- in your example above the function `find_files` with `file_regx = ".R"` still returns other types of data with R in the file type (e.g. ".Rd" and `RData`).
- The option to exclude multiple files/directories would be useful, as users may have several dodgy files/directories to remove. These could be passed in as a vector (e.g. `exclude_dirs = c("man", "inst")`) but then `grepl` doesn't work (because it only works on a single regex), therefore we would need to make our own inside the function (you probably have a better solution here):

```
exclude_files <- c("A", "B", "C")
pattern <- paste0(exclude_files, collapse = "|")

grepl(pattern = pattern, x = LETTERS) # letters is a built in dataset in R
```

**Comment by Smit-tay** [comment]
this regular expression
 "\\b(somefile\\.R|another_file\\.R)\\b" 

will exclude the specific files:  

1. somefile.R
2. another_file.R

whereas this : find_files(file_regx = ".*", exclude_files="\\.R", recursive=TRUE)
Will return a list of all files excluding those with names ending in ".R"

I suspect the regular expression use is more flexible than having to process a list of individual files names - even if it is a little harder for a novice to use.  Regular expressions just aren't that hard to master, there are regular expression generators online that could be used for people who have problems.
Of course, we could easily add parameters for file_exclusion_list and directory_exclusion_list.

**Comment by Smit-tay** [comment]
"\b(somefile\.R$|another_file\.R$)\b"

I reread your last message and noticed the bit about returning the . Rd files. 

That's also controllable via the regex.  The solution is above.  Note the dollar sign, which indicates end of string.

**Comment by RobertASmith** [comment]
I think you are right, if people struggle we can just point towards the regex generators

**Pull request merged**
